config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 }, uniqueness: { case_sensitive: false },
                    format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # This is the way to make is method a helper method otherwise it will not
  # available in view i.e. only helper methods is available in views.
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    unless logged_in?
      flash[:alert] = "You're not permitted to do so. Please login in."
      redirect_to login_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]
  before_action :require_user, except: %i[index show]
  before_action :require_same_user, only: %i[edit update destroy]

  def index
    # @articles = Article.all
    @articles = Article.paginate(page: params[:page], per_page: 2)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = 'Article was created successfully.'
      # redirect_to article_path(@article)
      redirect_to @article
    else
      render 'new'
    end
  end

  def show; end

  def edit; end

  def update
    if @article.update(article_params)
      flash[:notice] = 'Article was updated successfully.'
      # redirect_to article_path(@article)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    respond_to do |format|
      # format.html { redirect_to users_url }
      format.js {render :layout => false }
    end
    # redirect_to articles_path if @article.destroy
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = 'You can only edit/delete your own articles'
      redirect_to @article
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    # @session = Session.new
  end

  def create
    user = User.find_by(email: session_params[:email].downcase)
    if user && user.authenticate(session_params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Welcome back #{user.username}."
      redirect_to user_path(user.id)
    else
      flash.now[:alert] = 'There was something wrong with your login details'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :require_user, only: %i[edit update]
  before_action :require_same_user, only: %i[edit update destroy]

  def index
    # @users = User.all
    @users = User.paginate(page: params[:page], per_page: 2)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to the Alpha Blog #{@user.username}, you have successfully signed up."
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      flash[:notice] = 'Your account information was updated successfully.'
      # redirect_to article_path(@article)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def show
    # @articles = @user.articles
    @articles = @user.articles.paginate(page: params[:page], per_page: 2)
  end

  def destroy
    if @user.destroy
      session[:user_id] = nil if @user == current_user
      flash[:notice] = 'Your account information including your data has been deleted successfully.'
      redirect_to articles_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = 'You can only edit/delete your own account'
      redirect_to @user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    email_address = user.email
    # create the md5 hash
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    # compile URL which can be used in <img src="RIGHT_HERE"...
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: 'rounded shadow mx-auto d-block')
  end
end

app/views/articles/_article.html.erb
<div class="container">
	<div class="flickr_pagination">
		<%= will_paginate @articles, :container => false %>
	</div>
	<% @articles.each do |article| %>
		<div class="card text-center mt-4 shadow mb-5 bg-white rounded" id="<%= article.id %>">
			<div class="card-header font-italic">
				<% if article.user %>
					Article by <%= link_to article.user.username, user_path(article.user) %>
				<% end %>
			</div>
			<div class="card-body">
				<h5 class="card-title"><%= link_to article.title, article_path(article.id), class: "text-success" %></h5>
				<p class="card-text"><%= truncate(article.description,length:100) %></p>
				<%= link_to 'View', article_path(article.id), class:"btn btn-primary" %>
				<% if logged_in? && (current_user == article.user || current_user.admin?) %>
					<%= link_to 'Edit', edit_article_path(article.id), class:"btn btn-secondary" %>
					<%= link_to 'Delete', article_path(article.id), method: :delete, data: {confirm: "Are you sure?"}, remote: true, class:"btn btn-danger" %>
				<% end %>
			</div>
			<div class="card-footer text-muted">
				<small>Created <%= time_ago_in_words(article.created_at) %> ago , edited <%= time_ago_in_words(article.updated_at) %> ago</small>
			</div>
		</div>
	<% end %>
</div>

app/views/articles/_form.html.erb
<div class="container mt-5">

<%= render 'shared/errors', obj: @article %>
<%= form_with(model: @article, local: true, class: "shadow p-3 mb-5 bg-info rounded") do |f| %>
	<div class="form-group row">
		<%= f.label :title, class: "col-2 col-form-label text-light" %>
		<div class="col-10">
			<%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of Article" %>
		</div>
	</div>
	<div class="form-group row">
		<%= f.label :description, class: "col-2 col-form-label text-light" %>
		<div class="col-10">
			<%= f.text_area :description, rows:10, class: "form-control shadow rounded", placeholder: "Description of Article" %>
		</div>
	</div>
	<div class="form-group row justify-content-center">
		<%= f.submit class:"btn btn-primary" %>
	</div>
	
<% end %>
<%= link_to '[ Return to listing ]', articles_path, class: "row justify-content-center text-info"  %>
</div>

app/views/articles/destroy.js.erb
$("div#<%= article.id %>").remove();

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit Article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Listing All Articles</h1>

<%= render 'article' %>

<%= link_to 'Create new article', new_article_path %>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create A New Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1 class="text-center mt-4">Showing article details</h1>

<div class="container">
	<div class="card text-center mt-4 shadow mb-5 bg-white rounded">
		<div class="card-header font-italic">
			Article by <%= @article.user.username  if @article.user %>
			<%= link_to gravatar_for(@article.user), user_path(@article.user)  %>
		</div>
		<div class="card-body">
			<h5 class="card-title"><%= @article.title %></h5>
			<p class="card-text"><%= truncate(@article.description,length:100) %></p>
			<% if logged_in? && (current_user == @article.user || current_user.admin?) %>
				<%= link_to 'Edit', edit_article_path(@article.id), class:"btn btn-secondary" %>
				<%= link_to 'Delete', article_path(@article.id), method: :delete, data: {confirm: "Are you sure?"}, class:"btn btn-danger" %>
			<% end %>
		</div>
		<div class="card-footer text-muted">
			<small>Created <%= time_ago_in_words(@article.created_at) %> ago , edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
		</div>
	</div>
</div>

<%= link_to '[ Return to listing ]', articles_path, class: "row justify-content-center text-info"  %>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="flex-shrink-0 py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Copyright &copy; Your Website</small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
      <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
            <h4 class="alert-heading"> <%= msg %></h4>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
            </button>
      </div>
      <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="<%= root_path %>">Alpha Blog</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="<%= users_path %>">Bloggers<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Articles
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <% if logged_in? %>
                <a class="dropdown-item" href="<%= new_article_path %>">Creat New</a>
              <% end %>
              <a class="dropdown-item" href="<%= articles_path %>">List</a>
              <!-- <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a> -->
            </div>
          </li>
          <% if logged_in? %>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= "(Admin)" if current_user.admin? %>Settings
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="<%= user_path(current_user) %>">User</a>
                <a class="dropdown-item" href="<%= edit_user_path(current_user) %>">Account</a>
                <div class="dropdown-divider"></div>
                <%= link_to "Delete Account", user_path(current_user), method: :delete, data: {confirm: "You're going to delete your account are you sure?"}, class: "dropdown-item text-danger" %>
              </div>
            </li>
            <li class="nav-item">
              <%= link_to "Logout", logout_path, class: "nav-link", method: :delete %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Login", login_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign Up", signup_path, class: "nav-link" %>
            </li>
          <% end %>
          
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>

    <%= render 'layouts/messages' %>
    <%= yield %>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div id="page-content">
	<div class="jumbotron jumbotron-fluid text-center">
		<h1 class="display-4">Alpha Blog</h1>
		<p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
		<hr class="my-4">
		<p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
		<p class="lead">
		<%= link_to "Sign Up", signup_path, class: "btn btn-success btn-lg" %>
		</p>
	</div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
	<div class="alert alert-danger alert-dismissible fade show" role="alert">
		<h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved!</h4>
		<ul>
			<% obj.errors.full_messages.each do |msg| %>
				<li><%= msg %></l1>
			<% end %>
		</ul>
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
	</div>
<% end %>

app/views/users/_form.html.erb
<div class="container mt-5">

<%= render 'shared/errors', obj: @user %>

<%= form_with(model: @user, local: true, class: "shadow p-3 mb-5 bg-info rounded") do |f| %>
	<div class="form-group row">
		<%= f.label :username, class: "col-2 col-form-label text-light" %>
		<div class="col-10">
			<%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter Username" %>
		</div>
	</div>
	<div class="form-group row">
		<%= f.label :email, class: "col-2 col-form-label text-light" %>
		<div class="col-10">
			<%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Enter Email" %>
		</div>
	</div>
	<div class="form-group row">
		<%= f.label :password, class: "col-2 col-form-label text-light" %>
		<div class="col-10">
			<%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Enter Password" %>
		</div>
	</div>
	<div class="form-group row justify-content-center">
		<%= f.submit(@user.new_record? ? "Sign Up" : "Update Account", class:"btn btn-primary") %>
	</div>
	
<% end %>
<%= link_to '[ Return to listing ]', articles_path, class: "row justify-content-center text-info"  %>
</div>

app/views/users/_user.html.erb
<div class="container">
	<div class="flickr_pagination">
		<%= will_paginate @users, :container => false %>
	</div>
	<% @users.each do |user| %>
		<div class="card text-center mt-4 shadow mb-5 bg-white rounded">
			<div class="card-header font-italic">
				<%= link_to user.username, user_path(user) %>
			</div>
			<div class="card-body">
				<h5 class="card-title"><%= gravatar_for user, size: 150 %></h5>
				
				<p class="mt-2 card-text"><%= pluralize(user.articles.count, "article") %></p>
	 			<%= link_to 'View Profile', user_path(user.id), class:"btn btn-primary mt-2" %>
				<% if logged_in? %>
					<% if current_user == user %>
						<%= link_to 'Edit Profile', edit_user_path(user.id), class:"btn btn-secondary mt-2" %>
					<% end %>
					<% if current_user.admin? %>
						<%= link_to 'Delete Profile', user_path(user.id), method: :delete,data: {confirm: "Are you sure you want to delete user with all associated data?"}, class:"btn btn-danger mt-2" %>
					<% end %>
				<% end %>
			</div>
			<div class="card-footer text-muted">
				<small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
			</div>
		</div>
	<% end %>
</div>

app/views/users/destroy.js.erb
$("td#<%= user.id %>").remove();

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit User</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4">Alpha Bloggers</h1>

<%= render 'user' %>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign up for Alpha Blog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.username %>'s profile</h1>

<%= gravatar_for @user, size: 200 %>
<% if logged_in? && current_user == @user %>
	<div class="text-center mt-4">
		<%= link_to 'Edit Profile', edit_user_path(@user.id), class:"btn btn-info" %>
	</div>
<% end %>
<h4 class="text-center mt-4">Articles</h4>

<%= render 'articles/article' %>